# Docker compose pour un stock Wordpress - MariaDB et PHPMyAdmin
# Version des services à utiliser

version : "3.3"

# Déclaration des services à utiliser
services : 

  # Container avec Wordpress
  wordpress:
    image: wordpress
    restart: always
    ports:
      # La machine locale ouvre le port 8080 qui pointe vers le port 80 du container 
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: azertysio
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

    depends_on:
      - db

# container avec mariadb
  db:
    image: mariadb
    # comportement en cas de plantage
    restart: always

    # variable d'environnement
    environment:
    # mdp de l'user root
      MARIADB_ROOT_PASSWORD: azertysio


    # redirection de port
    ports:
      - 3308:3306


# container avec phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    restart: always
    # variable d'environnement
    environment:
    # mdp de l'user root
      PMA_HOST : db
      PMA_USER : root
      PMA_PASSWORD : azertysio
    ports:
      - 8081:80
    depends_on:
      - db
volumes : 
  wordpress : 
  db :